services:
 app:
  image: exercise_12.15
  build:
   context: ./todo-frontend
   dockerfile: dev.Dockerfile
  ports:
   - 3000:3000

 nginx:
  image: nginx:1.20.1
  ports:
   - 8080:80
  volumes:
   - ./nginx.conf:/etc/nginx/nginx.conf:ro
  depends_on:
   - app
